[package]
name = "first-positive-integer"
version = "0.1.0"
authors = ["Kieran Dewar <kldewar182@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
